apiVersion: v1
kind: Service
metadata:
  name: HelloApp-service
spec:
  selector:
    app: HelloApp
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30080
  type: NodePort
